services:
  mongodb:
    image: mongo:7-jammy
    container_name: devhouse-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: devhouse_dev
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
