export const defaultTechnologies = [
  {
    name: 'React',
    slug: 'react',
    categorySlug: 'frontend',
    description: {
      vi: 'Thư viện xây dựng giao diện người dùng tương tác cao, được sử dụng rộng rãi trên toàn cầu.',
      en: 'A premier library for building responsive, component-driven user interfaces.',
    },
    icon: 'react',
    websiteUrl: 'https://react.dev',
    order: 1,
    status: 'published',
  },
  {
    name: 'Node.js',
    slug: 'nodejs',
    categorySlug: 'backend-api',
    description: {
      vi: 'Môi trường thực thi JavaScript phía máy chủ, giúp xử lý các kết nối mạng tốc độ cao.',
      en: 'Server-side runtime optimized for building scalable and efficient networked applications.',
    },
    icon: 'nodejs',
    websiteUrl: 'https://nodejs.org',
    order: 2,
    status: 'published',
  },
  {
    name: 'Express',
    slug: 'express',
    categorySlug: 'backend-api',
    description: {
      vi: 'Khung ứng dụng máy chủ gọn nhẹ, linh hoạt cho việc phát triển các cổng giao tiếp API.',
      en: 'A fast, unopinionated minimalist web framework for crafting robust HTTP APIs.',
    },
    icon: 'express',
    websiteUrl: 'https://expressjs.com',
    order: 3,
    status: 'published',
  },
  {
    name: 'MongoDB',
    slug: 'mongodb',
    categorySlug: 'co-so-du-lieu',
    description: {
      vi: 'Cơ sở dữ liệu dạng tài liệu linh hoạt, phù hợp với hệ thống xử lý nội dung và dữ liệu biến đổi.',
      en: 'Document-oriented database offering dynamic schemas for modern, evolving applications.',
    },
    icon: 'mongodb',
    websiteUrl: 'https://www.mongodb.com',
    order: 4,
    status: 'published',
  },
  {
    name: 'Docker',
    slug: 'docker',
    categorySlug: 'ha-tang-devops',
    description: {
      vi: 'Nền tảng đóng gói ứng dụng độc lập, đảm bảo phần mềm vận hành nhất quán trên mọi môi trường máy chủ.',
      en: 'Standard platform to containerize software for consistent deployment across cloud environments.',
    },
    icon: 'docker',
    websiteUrl: 'https://www.docker.com',
    order: 5,
    status: 'published',
  },
  {
    name: 'Tailwind CSS',
    slug: 'tailwindcss',
    categorySlug: 'frontend',
    description: {
      vi: 'Hệ thống tiện ích thiết kế giao diện giúp xây dựng hệ thống màu sắc và bố cục nhất quán.',
      en: 'Utility-first styling system enabling standardized design tokens and responsive layouts.',
    },
    icon: 'tailwindcss',
    websiteUrl: 'https://tailwindcss.com',
    order: 6,
    status: 'published',
  },
];
