export const PERMISSIONS = [
  'dashboard:read',
  'pages:read',
  'pages:update',
  'settings:read',
  'settings:update',
  'navigation:read',
  'navigation:update',
  'services:read',
  'services:create',
  'services:update',
  'services:delete',
  'services:publish',
  'solutions:read',
  'solutions:create',
  'solutions:update',
  'solutions:delete',
  'solutions:publish',
  'projects:read',
  'projects:create',
  'projects:update',
  'projects:delete',
  'projects:publish',
  'technologies:read',
  'technologies:create',
  'technologies:update',
  'technologies:delete',
  'technologies:publish',
  'blog:read',
  'blog:create',
  'blog:update',
  'blog:delete',
  'blog:publish',
  'categories:read',
  'categories:manage',
  'tags:read',
  'tags:manage',
  'authors:read',
  'authors:manage',
  'redirects:read',
  'redirects:manage',
  'media:read',
  'media:upload',
  'media:update',
  'media:delete',
  'contact:read',
  'contact:update',
  'contact:delete',
  'contact:export',
  'users:read',
  'users:create',
  'users:update',
  'users:delete',
  'users:assign-roles',
  'roles:read',
  'roles:manage',
  'audit:read',
];

export const SEEDED_ROLES = {
  super_admin: {
    key: 'super_admin',
    name: { vi: 'Quản trị tối cao', en: 'Super Admin' },
    description: {
      vi: 'Toàn quyền kiểm soát hệ thống',
      en: 'Full system control',
    },
    isSystem: true,
    permissions: ['*'],
  },
  admin: {
    key: 'admin',
    name: { vi: 'Quản trị viên', en: 'Admin' },
    description: {
      vi: 'Quản trị toàn diện ngoại trừ quản lý phân quyền vai trò',
      en: 'Full management except role permissions management',
    },
    isSystem: false,
    permissions: PERMISSIONS.filter(p => p !== 'roles:manage'),
  },
  editor: {
    key: 'editor',
    name: { vi: 'Biên tập viên', en: 'Editor' },
    description: {
      vi: 'Biên tập và xuất bản nội dung, quản lý media và danh mục',
      en: 'Edit and publish content, manage media and categories',
    },
    isSystem: false,
    permissions: [
      'dashboard:read',
      'pages:read',
      'pages:update',
      'services:read',
      'services:create',
      'services:update',
      'services:delete',
      'services:publish',
      'solutions:read',
      'solutions:create',
      'solutions:update',
      'solutions:delete',
      'solutions:publish',
      'projects:read',
      'projects:create',
      'projects:update',
      'projects:delete',
      'projects:publish',
      'technologies:read',
      'technologies:create',
      'technologies:update',
      'technologies:delete',
      'technologies:publish',
      'blog:read',
      'blog:create',
      'blog:update',
      'blog:delete',
      'blog:publish',
      'categories:read',
      'categories:manage',
      'tags:read',
      'tags:manage',
      'authors:read',
      'authors:manage',
      'redirects:read',
      'redirects:manage',
      'media:read',
      'media:upload',
      'media:update',
      'media:delete',
    ],
  },
  support: {
    key: 'support',
    name: { vi: 'Hỗ trợ khách hàng', en: 'Support' },
    description: {
      vi: 'Xem dashboard và xử lý yêu cầu liên hệ',
      en: 'View dashboard and manage customer contact requests',
    },
    isSystem: false,
    permissions: ['dashboard:read', 'contact:read', 'contact:update'],
  },
};

export const hasPermission = (userPermissions = [], requiredPermission) => {
  if (!userPermissions || !Array.isArray(userPermissions)) return false;
  if (userPermissions.includes('*')) return true;
  if (!requiredPermission) return true;
  return userPermissions.includes(requiredPermission);
};
